In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf


#  RANDOM DATA GENERATION 

In [2]:
observations = 1000
xs = np.random.uniform(low=-10, high = 10, size=(observations,1))
xz = np.random.uniform(-10, 10, size=(observations,1))

generated_inputs = np.column_stack((xs,xz))
noise = np.random.uniform(-1,1,(observations,1))

generated_targets = 2*xs + 3*xz +5 + noise

np.savez( 'TF_intro', inputs = generated_inputs, targets=generated_targets)

# LOAD THE DATA

In [3]:
training_data = np.load(r'C:\Users\aryan\Desktop\datasets\TF_intro.npz')

In [4]:
training_data

In [5]:
input_size = 2
output_size = 1

model = tf.keras.Sequential([
                            tf.keras.layers.Dense(output_size)
                            ])

model.compile(optimizer='sgd', loss='mean_squared_error')

model.fit(training_data['inputs'], training_data['targets'] , epochs=200, verbose=2)

Epoch 1/200
32/32 - 0s - loss: 21.3337
Epoch 2/200
32/32 - 0s - loss: 4.4744
Epoch 3/200
32/32 - 0s - loss: 1.4527
Epoch 4/200
32/32 - 0s - loss: 0.6327
Epoch 5/200
32/32 - 0s - loss: 0.4111
Epoch 6/200
32/32 - 0s - loss: 0.3476
Epoch 7/200
32/32 - 0s - loss: 0.3374
Epoch 8/200
32/32 - 0s - loss: 0.3298
Epoch 9/200
32/32 - 0s - loss: 0.3222
Epoch 10/200
32/32 - 0s - loss: 0.3230
Epoch 11/200
32/32 - 0s - loss: 0.3236
Epoch 12/200
32/32 - 0s - loss: 0.3269
Epoch 13/200
32/32 - 0s - loss: 0.3255
Epoch 14/200
32/32 - 0s - loss: 0.3283
Epoch 15/200
32/32 - 0s - loss: 0.3240
Epoch 16/200
32/32 - 0s - loss: 0.3267
Epoch 17/200
32/32 - 0s - loss: 0.3220
Epoch 18/200
32/32 - 0s - loss: 0.3235
Epoch 19/200
32/32 - 0s - loss: 0.3237
Epoch 20/200
32/32 - 0s - loss: 0.3218
Epoch 21/200
32/32 - 0s - loss: 0.3257
Epoch 22/200
32/32 - 0s - loss: 0.3225
Epoch 23/200
32/32 - 0s - loss: 0.3248
Epoch 24/200
32/32 - 0s - loss: 0.3312
Epoch 25/200
32/32 - 0s - loss: 0.3232
Epoch 26/200
32/32 - 0s - loss: 0

#  Extract weight and bias

In [6]:
model.layers[0].get_weights()

[array([[2.0206544],
        [2.973028 ]], dtype=float32),
 array([5.0189757], dtype=float32)]

In [7]:
weight = model.layers[0].get_weights()[0]
weight

array([[2.0206544],
       [2.973028 ]], dtype=float32)

In [8]:
bias = model.layers[0].get_weights()[1]
bias

array([5.0189757], dtype=float32)

#  Making predictions


In [9]:
model.predict_on_batch(training_data['inputs']).round(1)


array([[ 24.4],
       [-17.8],
       [ 13.6],
       [-32.8],
       [  4. ],
       [-12.6],
       [-19.9],
       [  2. ],
       [  1.6],
       [ -2.5],
       [ -1. ],
       [-14.6],
       [-18.1],
       [-18.9],
       [ -8.2],
       [ 26.7],
       [ -1.2],
       [ -4.4],
       [ 31.1],
       [ 16.6],
       [  1.5],
       [-15.6],
       [  0.9],
       [  1.5],
       [-13.2],
       [ -8.6],
       [ 34. ],
       [-34.9],
       [  2.4],
       [-32.8],
       [ -5.5],
       [ 22.6],
       [ 24.6],
       [  9.5],
       [ -1.6],
       [  7.4],
       [ 19.6],
       [-10.7],
       [ 16.4],
       [ 28.4],
       [ 36.9],
       [  3.8],
       [ 12.8],
       [  1.4],
       [ 14.4],
       [  2.3],
       [ 32.7],
       [ 36.3],
       [-33.6],
       [ 15.2],
       [  4.1],
       [-41.9],
       [-27.1],
       [ -9.5],
       [ 10.9],
       [  3.2],
       [ -4.4],
       [  8. ],
       [ 16.3],
       [ 21.1],
       [ 32.3],
       [  3.6],
       [

In [10]:
training_data['targets'].round(1)

array([[ 25.5],
       [-17.7],
       [ 14.1],
       [-33. ],
       [  4.1],
       [-13.3],
       [-19. ],
       [  1.8],
       [  1.2],
       [ -3.5],
       [ -1.2],
       [-14.5],
       [-18. ],
       [-18. ],
       [ -7.4],
       [ 26.6],
       [ -0.9],
       [ -4.9],
       [ 31.5],
       [ 16.6],
       [  1.8],
       [-15.9],
       [  0.2],
       [  2.8],
       [-12.4],
       [ -7.9],
       [ 34.7],
       [-34.1],
       [  1.4],
       [-33.1],
       [ -5.9],
       [ 23.6],
       [ 25.1],
       [ 10.5],
       [ -2.3],
       [  7.3],
       [ 20.3],
       [-10.9],
       [ 15.9],
       [ 28.1],
       [ 37.9],
       [  4.6],
       [ 12.1],
       [  1.9],
       [ 15.4],
       [  2. ],
       [ 33.4],
       [ 36.3],
       [-34.2],
       [ 15.7],
       [  4.9],
       [-42.1],
       [-27.6],
       [ -8.6],
       [ 11.4],
       [  3.6],
       [ -4.1],
       [  8.5],
       [ 17.1],
       [ 21.1],
       [ 32.1],
       [  3.3],
       [


# Plotting outputs of algo against original data